version: '3.8'

services:
  ecommerceds:
    build:
      context: ./eCommerceDs
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Connection=Server=ecommerce-db;Database=ecommerceDs;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;MultipleActiveResultSets=true
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    depends_on:
      ecommerce-db:
        condition: service_healthy

  ecommerce-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    restart: unless-stopped
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "YourStrong@Passw0rd" -Q "SELECT 1" || exit 1
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s

volumes:
  sql_data: